# Generated by Django 3.2.16 on 2023-12-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeskripsi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
