# Generated by Django 3.2.16 on 2023-12-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeskripsi', '0004_auto_20231226_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='schedule_limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
