# Generated by Django 3.2.16 on 2023-12-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeskripsi', '0005_presence_schedule_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
